os:
  - osx

cache:
  directories:
  - $HOME/.electron

install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.30.1/install.sh | bash
  - source ~/.bashrc
  - nvm install 4.4.1
  - nvm use 4.4.1
  - npm i -g npm
  - rm -rf node_modules
  - npm install

branches:
  except:
    - website

script:
  - npm run test
  - npm run build
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then ./sig/import.sh && npm run make:darwin && node ./sig/publish-mac.js; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/92deafd1eb3a9871497b
    on_success: always
    on_failure: always
    on_start: never
